config/routes.rb
Personaldj::Application.routes.draw do
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  get "home/index"
  get "home/instructions"

  get "lists/pop-rock" => "lists#poprock"
  get "lists/rock" => "lists#rock"
  get "lists/indie" => "lists#indie"

  resources :lists do
    member do
      post :vote
    end
  end

  resources :categories

  resources :clubs do
    member do
      get 'new_list'
    end
  end

  resources :searches

  root :to => 'clubs#index'

end

app/models/club.rb
class Club < ActiveRecord::Base
  has_many :lists
  attr_accessible :name, :location, :contact_person, :telephone_number, :description,
                  :website
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  # GET /clubs
  # GET /clubs.json
  def index
    if current_user
      redirect_to home_index_path
    else
      @clubs = Club.all

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @clubs }
      end
    end
  end

  # GET /clubs/1
  # GET /clubs/1.json
  def show
    require 'open-uri'
    require 'json'

    @club = Club.find(params[:id])
    @lists = List.find(:all)

    @latest_accepted = JSON.parse(open("http://move.personal.dj/api/latest_successful_requests.json").read)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @club }
    end
  end

  # GET /clubs/new
  # GET /clubs/new.json
  def new
    @club = Club.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @club }
    end
  end

  def new_list
    @list = List.new
    @club = Club.find(params[:id])

    respond_to do |format|
      format.html # new_list.html.erb
      format.json { render json: @list }
    end
  end

  # GET /clubs/1/edit
  def edit
    @club = Club.find(params[:id])
  end

  # POST /clubs
  # POST /clubs.json
  def create
    @club = Club.new(params[:club])

    respond_to do |format|
      if @club.save
        format.html { redirect_to @club, notice: 'Club was successfully created.' }
        format.json { render json: @club, status: :created, location: @club }
      else
        format.html { render action: "new" }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clubs/1
  # PUT /clubs/1.json
  def update
    @club = Club.find(params[:id])

    respond_to do |format|
      if @club.update_attributes(params[:club])
        format.html { redirect_to @club, notice: 'Club was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clubs/1
  # DELETE /clubs/1.json
  def destroy
    @club = Club.find(params[:id])
    @club.destroy

    respond_to do |format|
      format.html { redirect_to clubs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/clubs_helper.rb
module ClubsHelper
  def club_profile_value(value)
    List.find(:all, :conditions => ["club_id = ? AND genre = ?", @club.id, value]).count
  end
end

app/views/clubs/_club.html.erb
<div class="well">
  <h2><%= link_to club.name, club %></h2>
  <div class="well well-mini">
    <p>Location: <%= club.location %></p>
    <p>Music profile: tbd</p>
    <p>Website: <%= link_to club.website, club.website, :target => "_blank" %></p>
    <p><%= link_to 'More info', "#", :class => "display_more_info" %></p>
    <p class="description_info"><%= club.description %></p>
  </div>
</div>

app/views/clubs/_club_profile_chart.html.erb
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
  google.load("visualization", "1", {packages:["corechart"]});
  google.setOnLoadCallback(drawChart);
  function drawChart() {
    var data = google.visualization.arrayToDataTable([
      ['Genre', 'Times played'],
      ['Pop', <%= club_profile_value(1) %> ],
      ['Rock', <%= club_profile_value(2) %>],
      ['Metal', <%= club_profile_value(3) %>],
      ['Dubstep', <%= club_profile_value(4) %>],
      ['Alternative', <%= club_profile_value(5) %>],
      ['R&B', <%= club_profile_value(6) %>],
      ['House', <%= club_profile_value(7) %>],
      ['Folk', <%= club_profile_value(8) %>],
      ['Indie', <%= club_profile_value(9) %>],
      ['Pop rock', <%= club_profile_value(10) %>],
      ['Ska', <%= club_profile_value(11) %>],
      ['Hip hop', <%= club_profile_value(12) %>],
      ['Drum & bass', <%= club_profile_value(13) %>],
      ['Techno', <%= club_profile_value(14) %>],
      ['Jazz', <%= club_profile_value(15) %>]
    ]);

    var options = {
      title: 'Overview requested genres',
      is3D: true,
    };

    var chart = new google.visualization.PieChart(document.getElementById('piechart_3d'));
    chart.draw(data, options);
  }
</script>

app/views/clubs/_form.html.erb
<%= form_for(@club) do |f| %>
  <% if @club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@club.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @club.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br/>
  <hr />
  <div class="field form-inline">
    <%= f.label :name, "Club name" %>:
    <%= f.text_field :name, :class => 'text_field' %>
  </div>
  <hr />
  <div class="field form-inline">
    <%= f.label :location, "City/Stad" %>:
    <%= f.text_field :location %>
  </div>
  <hr />
  <div class="field form-inline">
    <%= f.label :contact_person %>:
    <%= f.text_field :contact_person %>
  </div>
  <hr />
  <div class="field form-inline">
    <%= f.label :telephone_number %>:
    <%= f.text_field :telephone_number %>
  </div>
  <hr />
  <div class="field form-inline">
    <%= f.label :website, "Website link" %>:
    <%= f.text_field :website %>
  </div>
  <hr />
  <div class="field">
    <%= f.label :description, "Description:" %><br/>
    <%= f.text_area :description, :class => "text_area" %>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                clubs_path, :class => 'btn' %>
  </div>
<% end %>

app/views/clubs/_latest_accepted.html.erb
<h3>
  Latest Accepted songs
</h3>

<table class="table table-hover">
  <tr>
    <th>#</th>
    <th>Title</th>
    <th>Artist</th>
    <th>Genre</th>
    <th># Votes</th>
  </tr>

  <% my_awesome_counter = 0 %>
<% @lists.each do |l| %>
  <% @latest_accepted.each do |s| %>
    <% if s["name"].to_i == l.id %>
    <% my_awesome_counter += 1 %>
      <tr>
        <td><%= my_awesome_counter %></td>
        <td><%= l.title %></td>
        <td><%= l.artist %></td>
        <td><%= l.genre_viewer %></td>
        <td><%= s["points"] %></td>
      </tr>
    <% end %>
  <% end %>
<% end %>
</table>

app/views/clubs/edit.html.erb
<%- model_class = Club -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/clubs/index(old).html.erb
<%- model_class = Club -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @clubs.each do |club| %>
      <tr>
        <td><%= link_to club.id, club_path(club) %></td>
        <td><%= club.name %></td>
        <td><%=l club.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_club_path(club), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      club_path(club),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_club_path,
            :class => 'btn btn-primary' %>

app/views/clubs/index.html.erb
<head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="../assets/ico/favicon.png">
  <script type="text/javascript" src="chrome-extension://bfbmjmiodbnnpllbbbfblcplfjjepjdn/js/injected.js"></script>
</head>

  <body id="myBody" style="display:none">

    <div class="container-narrow">

      <div class="masthead">
        <ul class="nav nav-pills pull-right">
          <li class="active"><a href="#">Getting started</a></li>
          <li><%= link_to 'Search club', new_search_path %></li>
        <% if current_user %>
          <li><%= link_to 'Sign out', signout_path, id: "sign_out" %></li>
        <% else %>
          <li><%= link_to 'Sign in', "/auth/facebook", id: "sign_in" %></li>
        <% end %>
        </ul>
        <h3 class="muted">Personal DJ</h3>
      </div>

      <hr>

      <div class="jumbotron">
        <h1>Discover, share and enjoy music!</h1>
        <p class="lead">Wouldn't it be wonderful to create a community where new artists could share and promote their singles, where music fans could share their favorite songs...</p>
        <%= link_to 'Sign up today', "#", :class => "btn btn-large btn-success sign_up_button" %>
        <%= link_to 'Sign in', "/auth/facebook", :class => "btn btn-large btn-primary sign_in_button" %>
      </div>

      <div class="instructions">
        <%= render "home/instructions" %>
      </div>

      <hr>

      <div class="row-fluid sub_row">
        <div class="span6">
          <h4>What is it?</h4>
          <p>Personal DJ is a mobile application which provides music listeners the opportunity to play their favorite songs in nightclubs & bars. [read more]</p>
        </div>


        <div class="span6">
          <h4>How does it work?</h4>
          <p>The mobile application will allow visitors to vote for their favorite songs which the DJ will play. The app works with fixed playlists which you can build and share. [read more]</p>
        </div>
      </div>

      <div class="row-fluid sub_row">
        <div class="span6">
          <h4>Is it available in every club?</h4>
          <p>No, unfortunately not, a list of clubs & bars which have Personal DJ can be found <%= link_to 'here', "#" %> [read more]</p>
        </div>
        <div class="span6">
          <h4>Where can I get the app?</h4>
          <p>The app will be available at the Android web store, furthermore is the app available in your mobile browser. [read more]</p>
        </div>
      </div>

    <!--- #new sub row
      <div class="row-fluid sub_row">
        <div class="span6">
          <h4>Subheading</h4>
          <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
        </div>
        <div class="span6">
          <h4>Subheading</h4>
          <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
        </div>
      </div>
    --->



      <hr>

      <div class="footer">
        <p>© Personal DJ 2013 | <em>Number of clubs using Personal DJ: <%= @clubs.count %></em></p>
      </div>

    </div>
</body>

app/views/clubs/new.html.erb
<div class="container-narrow">
  <h1>New Club</h1>
  <%= render :partial => 'form' %>
</div>

app/views/clubs/new_list.html.erb
<div class="container-narrow">
  <%= form_for(@list) do |f| %>
    <% if @list.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

        <ul>
        <% @list.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <br/>
    <hr />

    <div class="field form-inline">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>
    <hr />
    <div class="field form-inline">
      <%= f.label :artist %><br />
      <%= f.text_field :artist %>
    </div>
    <hr />
    <div class="field form-inline">
      <%= f.label :genre %><br />
      <%= f.select(:genre, [['Pop', 1], ['Pop rock', 10], ['(Punk/Hard/Classic) Rock', 2], ['Metal', 3], ['Dubstep', 4], ['Alternative', 5], ['R&B', 6], ['House', 7], ['Folk', 8], ['Indie', 9], ['Ska', 11], ['Hip hop', 12], ['Drum & bass', 13], ['Techno', 14], ['Jazz', 15]], :prompt => "Music style") %>
    </div>
    <hr />
    <div class="field form-inline">
      <%= f.label :category %><br />
      <%= f.number_field :category %>
    </div>
    <hr />
    <div class="field form-inline">
      <%= f.label :listen_link, "Please put a Youtube, Spotify or Soundcloud link here (url) so others can listen to the song." %><br />
      <%= f.text_field :listen_link %>
    </div>
    <hr />
    <div class="field form-inline">
      <%= f.label :media_type %><br />
      <%= f.select(:media_type, [["Youtube", 1], ["Spotify", 2], ["Soundcloud", 3], ["Other", 4]], prompt: true) %>
    </div>
    <hr />
    <div class="field form-inline">
      <h4>Hidden fields</h4>
      <%= f.label :user_name %><br />
      <%= f.text_field :user_name, :value => current_user.name %>
    </div>
    <div class="field form-inline">
      <%= f.label :user_id %><br />
      <%= f.number_field :user_id, :value => current_user.uid %>
    </div>
    <div class="field form-inline">
      <%= f.label :club_id %><br />
      <%= f.number_field :club_id, :value => @club.id %>
    </div>
    <br/>
    <div class="actions">
      <%= f.submit "Share song", :class => "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/clubs/show.html.erb
<head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="../assets/ico/favicon.png">
  <script type="text/javascript" src="chrome-extension://bfbmjmiodbnnpllbbbfblcplfjjepjdn/js/injected.js"></script>
  <%= render "club_profile_chart" %>
</head>

  <body id="myBody" style="display:none">

    <div class="container-narrow">

      <div class="masthead">
        <ul class="nav nav-pills pull-right">
          <li><%= link_to 'Music lists', lists_path %></li>
          <li class="active"><a href="#">Activity feed</a></li>
          <li><a href="#">News</a></li>
        <% if current_user %>
          <li><%= link_to 'Sign out', signout_path, id: "sign_out" %></li>
        <% else %>
          <li><%= link_to 'Sign in', "/auth/facebook", id: "sign_in" %></li>
        <% end %>
        </ul>
        <h3 class="muted">Personal DJ</h3>
      </div>

      <hr>

      <h1><%= @club.name %> <% if @club.location.present? %>
        - <%= @club.location %>
      <% end %></h1>
      <hr />
      <%= simple_format @club.description %>
      <hr />
        <div id="piechart_3d" style="width: 450px; height: 250px;"></div>
      <hr />

      <%= render "latest_accepted" %>


    <!--- #new sub row
      <div class="row-fluid sub_row">
        <div class="span6">
          <h4>Subheading</h4>
          <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
        </div>
        <div class="span6">
          <h4>Subheading</h4>
          <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
        </div>
      </div>
    --->



      <hr>

      <div class="footer">
        <p>© Personal DJ 2013</p>
      </div>

    </div>
</body>

<!--
  <div class="form-actions">
    <%= link_to t('.back', :default => t("helpers.links.back")),
                clubs_path, :class => 'btn'  %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_club_path(@club), :class => 'btn' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                club_path(@club),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
    <%= link_to t('.new_list', :default => t("helpers.links.new_list")),
                new_list_club_path(@club), :class => 'btn btn-primary' %>
  </div>
-->