config/routes.rb
Personaldj::Application.routes.draw do
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  get "home/index"
  get "home/instructions"

  get "lists/pop-rock" => "lists#poprock"
  get "lists/rock" => "lists#rock"
  get "lists/indie" => "lists#indie"

  resources :lists do
    member do
      post :vote
    end
  end

  resources :categories

  resources :clubs do
    member do
      get 'new_list'
    end
  end

  resources :searches

  root :to => 'clubs#index'

end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :club

  attr_accessible :artist, :category, :title, :club_id, :user_name, :user_id,
                  :listen_link, :media_type, :genre

  has_reputation :votes, source: :user, aggregated_by: :sum

  def genre_viewer
    if genre == 1
      "Pop"
    elsif genre == 2
      "Rock"
    elsif genre == 3
      "Metal"
    elsif genre == 4
      "Dubstep"
    elsif genre == 5
      "Alternative"
    elsif genre == 6
      "R&B"
    elsif genre == 7
      "House"
    elsif genre == 8
      "Folk"
    elsif genre == 9
      "Indie"
    elsif genre == 10
      "Pop rock"
    elsif genre == 11
      "Ska"
    elsif genre == 12
      "Hip hop"
    elsif genre == 13
      "Drum & bass"
    elsif genre == 14
      "Techno"
    elsif genre == 15
      "Jazz"
    else
      "Trash"
    end
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lists }
    end
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @list = List.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/new
  # GET /lists/new.json
  def new
    @list = List.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/1/edit
  def edit
    @list = List.find(params[:id])
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(params[:list])

    respond_to do |format|
      if @list.save
        format.html { redirect_to club_path(@list.club_id), notice: 'List was successfully created.' }
        format.json { head :no_content }
      else
        format.html { render action: "new" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lists/1
  # PUT /lists/1.json
  def update
    @list = List.find(params[:id])

    respond_to do |format|
      if @list.update_attributes(params[:list])
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list = List.find(params[:id])
    @list.destroy

    respond_to do |format|
      format.html { redirect_to lists_url }
      format.json { head :no_content }
    end
  end

  def vote
    value = params[:type] == "up" ? 1 : -1
    @list = List.find(params[:id])
    @list.add_or_update_evaluation(:votes, value, current_user)
    redirect_to :back, notice: "Thank you for voting!"
  end

  def poprock
    @heat_list = List.find_with_reputation(:votes, :all, order: 'votes desc', :conditions => [ "genre = ?", 10 ], :limit => 20)
    @hot_list = List.find_with_reputation(:votes, :all, order: 'votes desc', :conditions => [ "genre = ?", 10 ], :limit => 25)
    @list = List.find_with_reputation(:votes, :all, order: 'votes desc', :conditions => [ "genre = ?", 10 ])

    respond_to do |format|
      format.html { render "lists/categories/pop_rock" }
      format.json { render json: @heat_list }
    end
  end

  def rock
    @heat_list = List.find_with_reputation(:votes, :all, order: 'votes desc', :conditions => [ "genre = ?", 2 ], :limit => 20)
    @hot_list = List.find_with_reputation(:votes, :all, order: 'votes desc', :conditions => [ "genre = ?", 2 ], :limit => 25)
    @list = List.find_with_reputation(:votes, :all, order: 'votes desc', :conditions => [ "genre = ?", 2 ])

    respond_to do |format|
      format.html { render "lists/categories/rock" }
      format.json { render json: @heat_list }
    end
  end

  def indie
    @heat_list = List.find_with_reputation(:votes, :all, order: 'votes desc', :conditions => [ "genre = ?", 9 ], :limit => 20)
    @hot_list = List.find_with_reputation(:votes, :all, order: 'votes desc', :conditions => [ "genre = ?", 9 ], :limit => 25)
    @list = List.find_with_reputation(:votes, :all, order: 'votes desc', :conditions => [ "genre = ?", 9 ])

    respond_to do |format|
      format.html { render "lists/categories/indie" }
      format.json { render json: @heat_list }
    end
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br/>
  <hr />

  <div class="field form-inline">
    <%= f.label :club_id, "Select club" %>:
    <%= f.collection_select :club_id, Club.all, :id, :name, prompt: true %>
  </div>
  <hr />
  <div class="field form-inline">
    <%= f.label :title %>:
    <%= f.text_field :title %>
  </div>
  <hr />
  <div class="field form-inline">
    <%= f.label :artist %>:
    <%= f.text_field :artist %>
  </div>
  <hr />
  <div class="field form-inline">
    <%= f.label :genre %>:
    <%= f.select(:genre, [['Pop', 1], ['Pop rock', 10], ['(Punk/Hard/Classic) Rock', 2], ['Metal', 3], ['Dubstep', 4], ['Alternative', 5], ['R&B', 6], ['House', 7], ['Folk', 8], ['Indie', 9], ['Ska', 11], ['Hip hop', 12], ['Drum & bass', 13], ['Techno', 14], ['Jazz', 15]], :prompt => "Music style") %>
  </div>
  <hr />
  <div class="field form-inline">
    <%= f.label :category %>:
    <%= f.number_field :category %>
  </div>
  <hr />
  <div class="field form-inline">
    <%= f.label :listen_link, "Please put a Youtube, Spotify or Soundcloud link here (url) so others can listen to the song." %>:
    <%= f.text_field :listen_link %>
  </div>
  <hr />
  <div class="field form-inline">
    <%= f.label :media_type %>:
    <%= f.select(:media_type, [["Youtube", 1], ["Spotify", 2], ["Soundcloud", 3], ["Other", 4]], prompt: true) %>
  </div>
  <hr />
  <div class="field form-inline">
    <h4>Hidden fields</h4>
    <%= f.label :user_name %>:
    <%= f.text_field :user_name, :value => current_user.name %>
  </div>
  <div class="field form-inline">
    <%= f.label :user_id %>:
    <%= f.number_field :user_id, :value => current_user.uid %>
  </div>
  <br/>
  <div class="actions">
    <%= f.submit "Share :)", :name => "create_button", :class => "btn btn-success" %>
  </div>
<% end %>

app/views/lists/_index.html.erb
<h3>
  Club list
  <%= link_to 'New song', new_list_club_path, :class => 'btn btn-primary new_list_button' %>
</h3>

<table class="table table-hover">
  <tr>
    <th>#</th>
    <th></th>
    <th></th>
    <th>Title</th>
    <th>Artist</th>
    <th>Category</th>
    <th># Votes</th>
    <th></th>

  </tr>

<% my_awesome_counter = 0 %>
<% @heat_list.each do |list| %>
  <% my_awesome_counter += 1 %>
  <tr>
    <td class="badge badge-success"><%= my_awesome_counter %></td>
    <td><%= link_to 'Listen', list.listen_link, :target => "_blank", :class => "btn btn-inverse btn-mini" %></td>
    <% if current_user && !current_user.voted_for?(list) %>
      <td><%= link_to "Vote", vote_list_path(list, type: "up"), method: "post", :class => "btn btn-mini btn-success"%></td>
    <% else %>
      <td></td>
    <!-- active down voting
      <td><%= link_to "Undo", vote_list_path(list, type: "down"), method: "post", :class => "btn btn-mini btn-danger" %></td>
    -->
    <% end %>
    <td><%= link_to list.title, list %></td>
    <td><%= list.artist %></td>
    <td><%= list.category %></td>
    <td><%= pluralize list.reputation_for(:votes).to_i, "vote" %></td>
    <td><%= link_to 'Promote', "#", :class => "btn btn-mini btn-inverse" %></td>
  </tr>
<% end %>

<% my_awesome_counter = 0 %>
<% @hot_list.each do |list| %>
  <% my_awesome_counter += 1 %>
    <% if my_awesome_counter > 20 %>
      <tr>
        <td class="badge badge-warning"><%= my_awesome_counter %></td>
        <td><%= link_to 'Listen', list.listen_link, :target => "_blank", :class => "btn btn-inverse btn-mini" %></td>
        <% if current_user && !current_user.voted_for?(list) %>
          <td><%= link_to "Vote", vote_list_path(list, type: "up"), method: "post", :class => "btn btn-mini btn-success"%></td>
        <% else %>
          <td></td>
        <!-- active down voting
          <td><%= link_to "Undo", vote_list_path(list, type: "down"), method: "post", :class => "btn btn-mini btn-danger" %></td>
        -->
        <% end %>
        <td><%= link_to list.title, list %></td>
        <td><%= list.artist %></td>
        <td><%= list.category %></td>
        <td><%= pluralize list.reputation_for(:votes).to_i, "vote" %></td>
        <td><%= link_to 'Promote', "#", :class => "btn btn-mini btn-inverse" %></td>
      </tr>
    <% end %>
<% end %>

<% my_awesome_counter = 0 %>
<% @list.each do |list| %>
  <% my_awesome_counter += 1 %>
    <% if my_awesome_counter > 25 %>
      <tr>
        <td class="badge badge-important"><%= my_awesome_counter %></td>
        <td><%= link_to 'Listen', list.listen_link, :target => "_blank", :class => "btn btn-inverse btn-mini" %></td>
        <% if current_user && !current_user.voted_for?(list) %>
          <td><%= link_to "Vote", vote_list_path(list, type: "up"), method: "post", :class => "btn btn-mini btn-success"%></td>
        <% else %>
          <td></td>
        <!-- active down voting
          <td><%= link_to "Undo", vote_list_path(list, type: "down"), method: "post", :class => "btn btn-mini btn-danger" %></td>
        -->
        <% end %>
        <td><%= link_to list.title, list %></td>
        <td><%= list.artist %></td>
        <td><%= list.category %></td>
        <td><%= pluralize list.reputation_for(:votes).to_i, "vote" %></td>
        <td><%= link_to 'Promote', "#", :class => "btn btn-mini btn-inverse" %></td>
      </tr>
    <% end %>
<% end %>

</table>

app/views/lists/_my_list.html.erb
<h3>
  My list
  <%= link_to 'Add new song', new_list_path, :class => "btn btn-primary new_list_button" %>
</h3>

<table class="table">
  <tr>
    <th>Votes</th>
    <th>Title</th>
    <th>Artist</th>
    <th>Club</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lists.each do |list| %>
  <tr>
    <td><%= pluralize list.reputation_for(:votes).to_i, "vote" %></td>
    <td><%= link_to list.title, list %></td>
    <td><%= list.artist %></td>
    <% @find_club_name.each do |c| %>
      <% if c.id = list.club_id %>
        <td><%= link_to c.name, club_path(list.club_id) %></td>
      <% end %>
    <% end %>
    <td><%= link_to 'Listen', list.listen_link, :target => "_blank", :class => "btn btn-inverse btn-mini" %></td>
    <td><%= link_to 'Promote', "#", :class => "btn btn-inverse btn-mini" %></td>
  </tr>
<% end %>
</table>

app/views/lists/_navbar_lists.html.erb
<ul class="nav nav-list">
  <li class="active"><a href="#">Home</a></li>
  <li class="nav-header">La lista de música</li>
  <li><%= link_to 'Pop/rock', controller: "lists", action: "poprock" %></li>
  <li><%= link_to 'Rock', controller: "lists", action: "rock" %></li>
  <li><%= link_to 'Indie', controller: "lists", action: "indie" %></li>
  <em>...more to follow...</em>
</ul>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index(old).html.erb
<h1>Listing lists</h1>

<table>
  <tr>
    <th>Artist</th>
    <th>Title</th>
    <th>Category</th>
    <th>Club</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lists.each do |list| %>
  <tr>
    <td><%= list.artist %></td>
    <td><%= list.title %></td>
    <td><%= list.category %></td>
    <td><%= list.club %></td>
    <td><%= link_to 'Show', list %></td>
    <td><%= link_to 'Edit', edit_list_path(list) %></td>
    <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New List', new_list_path %>

app/views/lists/index.html.erb
<head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="../assets/ico/favicon.png">
    <script type="text/javascript" src="chrome-extension://bfbmjmiodbnnpllbbbfblcplfjjepjdn/js/injected.js"></script>
</head>

  <body id="myBody" style="display:none">

  <div class="navbar_list">
    <%= render "navbar_lists" %>
  </div>

    <div class="container-narrow">

      <div class="masthead">
        <ul class="nav nav-pills pull-right">
          <li class="active"><%= link_to 'Music lists', lists_path %></li>
          <li><a href="#">Activity feed</a></li>
          <li><a href="#">News</a></li>
        <% if current_user %>
          <li><%= link_to 'Sign out', signout_path, id: "sign_out" %></li>
        <% else %>
          <li><%= link_to 'Sign in', "/auth/facebook", id: "sign_in" %></li>
        <% end %>
        </ul>
        <h3 class="muted">Personal DJ</h3>
      </div>

      <hr>

      <h2>Pagina met laatste activiteit van liedjes toegevoegd</h2>


    <!--- #new sub row
      <div class="row-fluid sub_row">
        <div class="span6">
          <h4>Subheading</h4>
          <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
        </div>
        <div class="span6">
          <h4>Subheading</h4>
          <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
        </div>
      </div>
    --->



      <hr>

      <div class="footer">
        <p>© Personal DJ 2013</p>
      </div>

    </div>
</body>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="../assets/ico/favicon.png">
  <script type="text/javascript" src="chrome-extension://bfbmjmiodbnnpllbbbfblcplfjjepjdn/js/injected.js"></script>
</head>

  <body id="myBody" style="display:none">

    <div class="container-narrow">

      <div class="masthead">
        <ul class="nav nav-pills pull-right">
          <li class="active"><a href="#">Activity feed</a></li>
          <li><a href="#">News</a></li>
        <% if current_user %>
          <li><%= link_to 'Sign out', signout_path, id: "sign_out" %></li>
        <% else %>
          <li><%= link_to 'Sign in', "/auth/facebook", id: "sign_in" %></li>
        <% end %>
        </ul>
        <h3 class="muted">Personal DJ</h3>
      </div>

      <hr>

      <p id="notice"><%= notice %></p>

      <p>
        <b>Title:</b>
        <%= @list.title %>
      </p>

      <p>
        <b>Artist:</b>
        <%= @list.artist %>
      </p>

      <p>
        <b>Genre:</b>
        <%= @list.genre_viewer %>
      </p>

      <p>
        <b>Category:</b>
        <%= @list.category %>
      </p>

      <p>
        <b>Club:</b>
        <%= @list.club_id %>
      </p>

      <!-- if someone edits the song, he/she can change the title after gathering many votes, do we want that?
        <%= link_to 'Edit song', edit_list_path(@list), :class => 'btn btn-primary' %>
      -->

      <hr>

      <div class="footer">
        <p>© Personal DJ 2013</p>
      </div>

    </div>
</body>